### ISSUE TITLE
Update to use "recheck" instead of "redos" lib

### ISSUE THREAD

**Issue by forivall** [MakeNowJust-Labo/eslint-plugin-redos#3]
Seems that you changed the name of `@makenowjust-labo/redos` to `@makenowjust-labo/recheck` [since 2.0.0](https://github.com/MakeNowJust-Labo/recheck/blob/main/CHANGELOG.md#200-2021-02-01).

I presume that [`resolutions`](https://yarnpkg.com/configuration/manifest/#resolutions) can be used as a workaround for now? (for yarn users), as it doesnt appear that the api has changed. But it would be nice to update it. (either you or a PR)

**Comment by MakeNowJust** [comment]
I'm working to improve recheck and have no time for this eslint plugin. But updating deps seems a light task, I will try it this weekend.

**Comment by forivall** [comment]
yeah, recheck is great! i've found it super useful when [eslint-plugin-security](https://github.com/nodesecurity/eslint-plugin-security) (uses [safe-regex](https://github.com/davisjam/safe-regex)) is giving false positives on some regexes. Thanks so much for your work!

**Comment by MakeNowJust** [comment]
v1.2.0 is released.

https://github.com/MakeNowJust-Labo/eslint-plugin-redos/releases/tag/v1.2.0

Thank you!
